version: "3.2"

services:
  database: 
    image: postgres
    container_name: database_postgress
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=yt_permission
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: nodetest
    restart: always
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database


volumes:
  pgdata:
    driver: local